/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#b15f00",
        "on-tertiary-fixed": "#2f1500",
        "primary-container": "#be543c",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdcc3",
        "surface-tint": "#a13e28",
        "secondary-fixed": "#b0f1c7",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002111",
        "secondary-fixed-dim": "#95d4ac",
        "on-secondary-fixed-variant": "#0f5132",
        "secondary": "#2d6a48",
        "on-surface": "#131b2e",
        "surface-container-low": "#f2f3ff",
        "surface-bright": "#faf8ff",
        "background": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#822714",
        "secondary-container": "#b0f1c7",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-primary-container": "#fffbff",
        "primary": "#9e3c26",
        "primary-fixed-dim": "#ffb4a3",
        "inverse-primary": "#ffb4a3",
        "on-tertiary": "#ffffff",
        "tertiary": "#8d4b00",
        "outline": "#8a726c",
        "surface-container-high": "#e2e7ff",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed-dim": "#ffb77d",
        "on-primary-fixed": "#3d0600",
        "primary-fixed": "#ffdad2",
        "on-error-container": "#93000a",
        "surface-container": "#eaedff",
        "on-surface-variant": "#57423d",
        "on-secondary-container": "#33704e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "outline-variant": "#ddc0ba",
        "surface-variant": "#dae2fd",
        "on-primary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "on-background": "#131b2e",
        "on-tertiary-container": "#fffbff",
        "surface": "#faf8ff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xl": "3rem",
        "space-2xs": "0.25rem",
        "space-xl": "2rem",
        "space-xs": "0.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin-desktop": "2.5rem",
        "margin-mobile": "1rem",
        "space-3xl": "4rem",
        "space-sm": "0.75rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Epilogue", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Epilogue", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-md": ["18px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
